### PR TITLE
Use theme color for no events page

### PR DESCRIPTION
**Pull request by q-hung**
Not it looks more consistent with theme color.

Screen Shot 2019-12-26 at 9 00 45
Screen Shot 2019-12-26 at 9 00 50

### CODE REVIEW

**Review by eralpkaraduman — COMMENTED** [review]
is `accentColor` different than `textTheme.caption.color`? Can't see the difference 🤔

**Comment by q-hung** [comment]
@eralpkaraduman I didn't update the screenshot, but currently it looks like this in my simulator
Screen Shot 2020-01-08 at 23 14 13

**Comment by eralpkaraduman** [comment]
Alright now i see! Sorry was a bit confused to tell the difference.
So, on development in dark mode it is bright orange.
With your change it is gray in also in dark mode.

I totally agree that it's better in gray.

If you can resolve the conflicts we can merge this imo.

**Comment by q-hung** [comment]
@eralpkaraduman Done. I resolved the conflict.

**Comment by q-hung** [comment]
@eralpkaraduman actually for some reasons, the `no_events_overlay` file was deleted in development. Was there something wrong with git?

**Comment by eralpkaraduman** [comment]
> @eralpkaraduman actually for some reasons, the `no_events_overlay` file was deleted in development. Was there something wrong with git?

I refactored it a bit to be more generic, then i reused it for the case when user skipped the initial setup.

it has a new name `event_list_overlay`
https://github.com/eralpkaraduman/event_dot_pizza/blob/development/lib/widgets/event_list_overlay.dart

**Comment by q-hung** [comment]
@eralpkaraduman I edit the right file now.
Screen Shot 2020-01-09 at 14 42 48
Screen Shot 2020-01-09 at 14 42 54

**Review by eralpkaraduman — APPROVED** [review]
LGTM 👍 
thanks!

**Comment by q-hung** [comment]
@eralpkaraduman btw, could you please grant me write permission, so that I don't need to sync two remotes on my working directory?

**Pull request merged**
